# Generated by Django 5.2.6 on 2025-09-26 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, verbose_name='URL (YouTube u otro)')),
                ('duracion', models.CharField(blank=True, help_text='Ej: 12:34', max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('videos_inscritos', models.ManyToManyField(blank=True, related_name='estudiantes', to='cursos.video')),
            ],
        ),
    ]
